### ISSUE TITLE
--kernel option not working

### ISSUE THREAD

**Issue by rlzijdeman** [Calysto/calysto_prolog#4]
Hi, I installed calysto_prolog using pip. The readme mentions the kernel is installed automatically, but I get `No such kernel named calysto_prolog` (full error log attached). Is there something else I would need to setup?

Best,

Richard
[no_kernel_log.txt](https://github.com/Calysto/calysto_prolog/files/1132882/no_kernel_log.txt)

**Comment by dsblank** [comment]
Did you follow all of the steps in the README? Make sure that if you use pip, that it is connected to the same Python that jupyter is using (in your case that looks like python3.6). So, that might mean using "pip3.6" for example.

**Comment by YnievesDotNet** [comment]
i see other error
 Unrecognized flag: '--kernel'??

using the last version today.
Yoinier, Thanks.

**Comment by dsblank** [comment]
`--kernel` is a flag given at the command line to `jupyter console` like this:

```shell
jupyter console --kernel calysto_prolog
```

**Comment by YnievesDotNet** [comment]
I'm using in this mode:

`jupyter notebook --kernel calysto_prolog`

because not showing the calysto_prolog kernel in the list, only are visible, python, text, and other defaults.

After use your recomendation, then now is visible the kernel caly..., why?

Is required after install any kernel run first in console??

Thanks.

**Comment by dsblank** [comment]
`--kernel` is a flag to `jupyter console` not `jupyter notebook`.

**Comment by mattdodge** [comment]
@dsblank The documentation in this repo indicates otherwise, that's why there was confusion. I ran into the same problem. I will PR for the doc update.
